# Generated by Django 3.2 on 2021-05-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cerealimage',
            old_name='candy',
            new_name='cereal',
        ),
    ]
