# Generated by Django 3.2 on 2021-05-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0002_rename_candy_cerealimage_cereal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cereal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cereal.cerealcategory'),
        ),
    ]
