# Generated by Django 3.2 on 2021-05-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0004_auto_20210507_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='cereal',
            name='ingredients',
            field=models.CharField(default='', max_length=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cereal',
            name='sugar',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cereal',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
