# Generated by Django 3.2 on 2021-05-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0005_auto_20210510_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cereal',
            name='description',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
