# Generated by Django 3.2 on 2021-05-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0002_rename_candy_cerealimage_cereal'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_cereal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cereal.cereal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
