# Generated by Django 3.2 on 2021-05-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0004_auto_20210507_1118'),
        ('order', '0004_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cereal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cereal.cereal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
