# Generated by Django 3.2 on 2021-05-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210507_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
